# Generated by Django 5.2.5 on 2025-08-12 08:45

from django.db import migrations, models

import iscc_hub.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "seq",
                    iscc_hub.fields.SequenceField(
                        help_text="Gapless sequence number for events",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Created"), (2, "Updated"), (3, "Deleted")],
                        db_index=True,
                        default=1,
                        help_text="Type of event (1=CREATED, 2=UPDATED, 3=DELETED)",
                    ),
                ),
                (
                    "iscc_id",
                    iscc_hub.fields.IsccIDField(
                        db_index=True,
                        help_text="ISCC-ID assigned to the declaration",
                        max_length=8,
                    ),
                ),
                (
                    "iscc_note",
                    models.JSONField(help_text="The logged IsccNote as JSON"),
                ),
                (
                    "event_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this event was logged (updates/deletes differ from ISCC-ID timestamp)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "db_table": "iscc_event",
                "ordering": ["seq"],
                "indexes": [
                    models.Index(fields=["iscc_id", "seq"], name="iscc_event_iscc_id_d8e0cb_idx"),
                    models.Index(fields=["event_time"], name="iscc_event_event_t_51f1ce_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="IsccDeclaration",
            fields=[
                (
                    "iscc_id",
                    iscc_hub.fields.IsccIDField(
                        help_text="ISCC-ID - the unique timestamp identifier",
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_seq",
                    models.BigIntegerField(
                        db_index=True,
                        help_text="Sequence number of the latest Event affecting this declaration",
                        unique=True,
                    ),
                ),
                (
                    "iscc_code",
                    models.CharField(
                        db_index=True,
                        help_text="ISCC-CODE identifying the content",
                        max_length=256,
                    ),
                ),
                (
                    "datahash",
                    models.CharField(
                        db_index=True,
                        help_text="Blake3 multihash of the content (1e20 prefix + hash)",
                        max_length=72,
                    ),
                ),
                (
                    "nonce",
                    models.CharField(
                        db_index=True,
                        help_text="128-bit hex nonce preventing replay attacks",
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "actor",
                    models.CharField(
                        db_index=True,
                        help_text="Ed25519 public key of the declaring actor",
                        max_length=128,
                    ),
                ),
                (
                    "gateway",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Gateway URL or URI template for metadata discovery",
                        max_length=2048,
                    ),
                ),
                (
                    "metahash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Blake3 hash of seed metadata (optional commitment)",
                        max_length=72,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="When this declaration was last modified",
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Soft delete flag - true if declaration has been deleted",
                    ),
                ),
                (
                    "redacted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Admin redaction flag - disables resolution of malicious declarations",
                    ),
                ),
            ],
            options={
                "verbose_name": "Declaration",
                "verbose_name_plural": "Declarations",
                "db_table": "iscc_declaration",
                "indexes": [
                    models.Index(
                        fields=["iscc_code", "-iscc_id"],
                        name="iscc_declar_iscc_co_c57a16_idx",
                    ),
                    models.Index(
                        fields=["datahash", "-iscc_id"],
                        name="iscc_declar_datahas_59615d_idx",
                    ),
                    models.Index(
                        fields=["actor", "-iscc_id"],
                        name="iscc_declar_actor_8874e1_idx",
                    ),
                    models.Index(
                        fields=["actor", "iscc_code"],
                        name="iscc_declar_actor_f3dfae_idx",
                    ),
                    models.Index(
                        fields=["actor", "datahash"],
                        name="iscc_declar_actor_544d41_idx",
                    ),
                    models.Index(
                        fields=["deleted", "-iscc_id"],
                        name="iscc_declar_deleted_fafc43_idx",
                    ),
                    models.Index(
                        fields=["redacted", "-iscc_id"],
                        name="iscc_declar_redacte_91cdd5_idx",
                    ),
                    models.Index(
                        fields=["event_seq", "deleted"],
                        name="iscc_declar_event_s_610b12_idx",
                    ),
                ],
            },
        ),
    ]
