# Generated by Django 6.0.6 on 2026-06-08 21:28

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import iscc_hub.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hub",
            fields=[
                (
                    "hub_id",
                    models.PositiveSmallIntegerField(
                        help_text="Hub identifier (0-4095) - unique network identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pubkey",
                    iscc_hub.fields.PubkeyField(
                        db_index=True,
                        help_text="Ed25519 public key of the hub for signature verification",
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="Base URL of the hub API endpoint (e.g. https://hub.example.com)",
                        max_length=2048,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this hub is currently active on the network",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hub",
                "verbose_name_plural": "Hubs",
                "db_table": "iscc_hub",
            },
        ),
        migrations.CreateModel(
            name="IsccDeclaration",
            fields=[
                (
                    "iscc_id",
                    iscc_hub.fields.IsccIDField(
                        help_text="ISCC-ID - the unique timestamp identifier",
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "iscc_code",
                    models.CharField(
                        db_index=True,
                        help_text="ISCC-CODE identifying the content",
                        max_length=256,
                    ),
                ),
                (
                    "datahash",
                    iscc_hub.fields.HexField(
                        db_index=True,
                        help_text="Blake3 multihash of the content (1e20 prefix + hash)",
                        max_length=34,
                    ),
                ),
                (
                    "nonce",
                    iscc_hub.fields.HexField(
                        db_index=True,
                        help_text="128-bit hex nonce preventing replay attacks",
                        max_length=16,
                        unique=True,
                    ),
                ),
                (
                    "pubkey",
                    iscc_hub.fields.PubkeyField(
                        db_index=True,
                        help_text="Ed25519 public key of the declaring actor",
                        max_length=32,
                    ),
                ),
                (
                    "controller",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="DID or W3C CID Document URL identifying the key controller",
                        max_length=2048,
                    ),
                ),
                (
                    "gateway",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Gateway URL or URI template for metadata discovery",
                        max_length=2048,
                    ),
                ),
                (
                    "metahash",
                    iscc_hub.fields.HexField(
                        blank=True,
                        db_index=True,
                        help_text="Blake3 hash of seed metadata (optional commitment)",
                        max_length=34,
                        null=True,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_index=True,
                        help_text="When this declaration was last modified",
                    ),
                ),
                (
                    "redacted",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Admin redaction flag - disables resolution of malicious declarations on this HUB",
                    ),
                ),
            ],
            options={
                "verbose_name": "Declaration",
                "verbose_name_plural": "Declarations",
                "db_table": "iscc_declaration",
            },
        ),
        migrations.CreateModel(
            name="LogRecord",
            fields=[
                (
                    "index",
                    models.BigIntegerField(
                        help_text="Zero-based leaf index (sequence number); the first record is 0",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "record",
                    models.BinaryField(
                        help_text="JCS-canonical log-entry envelope bytes (the leaf preimage)"
                    ),
                ),
                (
                    "iscc_id",
                    iscc_hub.fields.IsccIDField(
                        db_index=True,
                        help_text="ISCC-ID carried by the record",
                        max_length=8,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("declaration", "Declaration"),
                            ("deletion", "Deletion"),
                        ],
                        db_index=True,
                        help_text="Record type derived from the note schema (declaration|deletion)",
                        max_length=11,
                    ),
                ),
                (
                    "nonce",
                    iscc_hub.fields.HexField(
                        help_text="128-bit hex nonce; unique across all records",
                        unique=True,
                    ),
                ),
                (
                    "datahash",
                    iscc_hub.fields.HexField(
                        db_index=True,
                        help_text="Blake3 multihash of the declared content",
                    ),
                ),
                (
                    "pubkey",
                    iscc_hub.fields.PubkeyField(
                        db_index=True,
                        help_text="Ed25519 public key of the declaring actor",
                        max_length=32,
                    ),
                ),
                (
                    "event_time",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Hub microsecond time when the record was sequenced",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log Record",
                "verbose_name_plural": "Log Records",
                "db_table": "iscc_logrecord",
            },
        ),
        migrations.CreateModel(
            name="LogState",
            fields=[
                (
                    "hub_id",
                    models.PositiveSmallIntegerField(
                        help_text="Hub identifier (0-4095); matches settings.ISCC_HUB_ID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tree_size",
                    models.BigIntegerField(
                        default=0,
                        help_text="Number of committed records; the next 0-based leaf index equals this value",
                    ),
                ),
                (
                    "last_timestamp_us",
                    models.BigIntegerField(
                        default=0,
                        help_text="High-water mark of the Hub microsecond clock for monotonic ISCC-IDs",
                    ),
                ),
                (
                    "checkpoint",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Latest published C2SP signed-note checkpoint over the log (text)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log State",
                "verbose_name_plural": "Log State",
                "db_table": "iscc_logstate",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="PubKey",
            fields=[
                (
                    "pubkey",
                    models.CharField(
                        help_text="Ed25519 public key",
                        max_length=48,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable label for this key",
                        max_length=255,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this key is currently authorized",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User account managing this key (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pubkeys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Public Key",
                "verbose_name_plural": "Public Keys",
                "db_table": "iscc_pubkey",
            },
        ),
    ]
