# Generated by Django 5.2.5 on 2025-08-12 04:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("iscc_hub", "0001_initial"),
    ]

    operations = []
