"""
Known-answer tests for iscc_hub.merkle against the Go reference vectors.

The vectors in tests/vectors/tlog_kat.json are generated by conformance/genkat
using the Go reference libraries (golang.org/x/mod/sumdb/tlog and
github.com/transparency-dev/tessera). These tests assert the pure-Python
implementation reproduces the reference roots, hash tiles, entry bundles, and
inclusion/consistency proofs byte-for-byte — no Go needed at test time.
"""

import json
from functools import lru_cache
from pathlib import Path

import pytest

from iscc_hub import merkle

VECTORS_PATH = Path(__file__).resolve().parent / "vectors" / "tlog_kat.json"


@lru_cache(maxsize=1)
def _vectors():
    # type: () -> dict
    """Load and cache the checked-in KAT vectors."""
    return json.loads(VECTORS_PATH.read_text())


def _record(i):
    # type: (int) -> bytes
    """Return the canonical KAT leaf preimage for index i."""
    return f"iscc-log-entry-{i}".encode()


@lru_cache(maxsize=1)
def _all_records():
    # type: () -> list[bytes]
    """Build all KAT record byte strings up to the largest vector size."""
    max_size = max(_vectors()["sizes"])
    return [_record(i) for i in range(max_size)]


@lru_cache(maxsize=1)
def _all_leaf_hashes():
    # type: () -> tuple[bytes, ...]
    """Build all KAT leaf hashes up to the largest vector size."""
    return tuple(merkle.leaf_hash(r) for r in _all_records())


def test_empty_root_is_sha256_of_empty():
    # type: () -> None
    """The empty-tree root is SHA-256 of the empty string (RFC 6962)."""
    assert merkle.EMPTY_ROOT.hex() == "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
    assert merkle.tree_head([]).hex() == _vectors()["roots"]["0"]


def test_tree_head_matches_reference_roots():
    # type: () -> None
    """tree_head reproduces the Go reference tree heads for every vector size."""
    leaves = _all_leaf_hashes()
    for size_str, expected in _vectors()["roots"].items():
        size = int(size_str)
        assert merkle.tree_head(list(leaves[:size])).hex() == expected, f"root mismatch at size {size}"


def test_hash_tiles_match_reference():
    # type: () -> None
    """hash_tile reproduces every reference hash tile byte-for-byte."""
    leaves = _all_leaf_hashes()
    for size_str, tiles in _vectors()["hash_tiles"].items():
        for path, expected_hex in tiles.items():
            level, index, width = _parse_hash_tile_path(path)
            sub = 1 << (level * merkle.TILE_HEIGHT)
            actual_w = width if width else merkle.TILE_WIDTH
            base = index * merkle.TILE_WIDTH * sub
            local = list(leaves[base : base + actual_w * sub])
            assert merkle.hash_tile(level, local).hex() == expected_hex, f"tile {path} (size {size_str})"


def test_entry_bundles_match_reference():
    # type: () -> None
    """entry_bundle reproduces every reference entry bundle byte-for-byte."""
    records = _all_records()
    for size_str, bundles in _vectors()["entry_bundles"].items():
        for path, expected_hex in bundles.items():
            index, width = merkle.parse_tile_index(path[len("tile/entries/") :])
            actual_w = width if width else merkle.ENTRY_BUNDLE_WIDTH
            start = index * merkle.ENTRY_BUNDLE_WIDTH
            chunk = records[start : start + actual_w]
            assert merkle.entry_bundle(chunk).hex() == expected_hex, f"bundle {path} (size {size_str})"


def test_inclusion_proofs_match_reference_and_verify():
    # type: () -> None
    """inclusion_proof reproduces reference proofs and reconstructs the root."""
    leaves = _all_leaf_hashes()
    for entry in _vectors()["inclusion_proofs"]:
        size, index = entry["size"], entry["index"]
        proof = merkle.inclusion_proof(index, list(leaves[:size]))
        assert [h.hex() for h in proof] == entry["proof"], f"inclusion proof {index}/{size}"
        leaf = leaves[index]
        assert leaf.hex() == entry["leaf_hash"]
        root = merkle.root_from_inclusion_proof(leaf, index, size, proof)
        assert root.hex() == entry["root"]


def test_consistency_proofs_match_reference():
    # type: () -> None
    """consistency_proof reproduces the reference consistency proofs."""
    leaves = _all_leaf_hashes()
    for entry in _vectors()["consistency_proofs"]:
        m, n = entry["m"], entry["n"]
        proof = merkle.consistency_proof(m, list(leaves[:n]))
        assert [h.hex() for h in proof] == entry["proof"], f"consistency proof {m}->{n}"


def test_inclusion_proof_rejects_out_of_range():
    # type: () -> None
    """inclusion_proof and root_from_inclusion_proof reject bad indices."""
    leaves = list(_all_leaf_hashes()[:3])
    with pytest.raises(ValueError):
        merkle.inclusion_proof(3, leaves)
    with pytest.raises(ValueError):
        merkle.root_from_inclusion_proof(leaves[0], 5, 3, [])


def test_root_from_inclusion_proof_wrong_size_raises():
    # type: () -> None
    """A proof of the wrong length is rejected."""
    leaves = list(_all_leaf_hashes()[:4])
    proof = merkle.inclusion_proof(1, leaves)
    with pytest.raises(ValueError):
        merkle.root_from_inclusion_proof(leaves[1], 1, 4, proof + [b"\x00" * 32])


def test_consistency_proof_out_of_range_and_equal():
    # type: () -> None
    """consistency_proof returns [] for equal sizes and rejects bad old_size."""
    leaves = list(_all_leaf_hashes()[:4])
    assert merkle.consistency_proof(4, leaves) == []
    with pytest.raises(ValueError):
        merkle.consistency_proof(0, leaves)
    with pytest.raises(ValueError):
        merkle.consistency_proof(5, leaves)


def test_path_codec_round_trip():
    # type: () -> None
    """format/parse of tile indices round-trips, including thousands grouping."""
    assert merkle.format_index(0) == "000"
    assert merkle.format_index(67) == "067"
    assert merkle.format_index(273) == "273"
    assert merkle.format_index(1234067) == "x001/x234/067"
    assert merkle.tile_path(0, 0, 0) == "tile/0/000"
    assert merkle.tile_path(1, 1, 17) == "tile/1/001.p/17"
    assert merkle.entries_path(273, 112) == "tile/entries/273.p/112"
    for n in (0, 5, 67, 255, 273, 1000, 1234067):
        for w in (0, 1, 112, 255):
            idx, width = merkle.parse_tile_index(merkle.format_index(n) + (f".p/{w}" if w else ""))
            assert (idx, width) == (n, w)


def test_parse_tile_index_rejects_malformed():
    # type: () -> None
    """parse_tile_index rejects malformed encodings."""
    bad = [
        "x001",  # last group must not be x-prefixed
        "1/000",  # non-x prefix on a leading group
        "0000",  # group not 3 digits
        "00a",  # non-digit group
        "000.p/0",  # width below range
        "000.p/256",  # width above range
        "000.p/x",  # non-numeric width
        "x12/000",  # leading group not three digits
        "000.p",  # partial marker with no width segment
    ]
    for tail in bad:
        with pytest.raises(ValueError):
            merkle.parse_tile_index(tail)


def _parse_hash_tile_path(path):
    # type: (str) -> tuple[int, int, int]
    """Parse a 'tile/<L>/<tail>' path into (level, index, width)."""
    rest = path[len("tile/") :]
    level_str, _, tail = rest.partition("/")
    index, width = merkle.parse_tile_index(tail)
    return int(level_str), index, width
