openapi: 3.1.0
info:
  title: ISCC-HUB API
  description: Sign, timestamp, and discover content with ISCC-IDs
  version: 0.1.0
  x-logo:
    url: "/img/iscc-logo-white.png"
    backgroundColor: "#0054b2"
    altText: "International Standard Content Code (ISCC) - Logo"
paths:
  /declaration:
    post:
      summary: Declare ISCC-CODE
      description: |
        Submit an IsccNote for declaration. The server validates the submission,
        sequences it in the declaration log, and returns an IsccReceipt as a verifiable credential.

        **Duplicate Protection:** By default, the server rejects duplicate declarations
        (same datahash) with a 409 Conflict error. To force a duplicate declaration,
        include the `X-Force-Declaration: true` header.
      operationId: declare
      parameters:
        - name: X-Force-Declaration
          in: header
          required: false
          schema:
            type: string
            enum: ["true", "1"]
          description: |
            Set to "true" or "1" to bypass duplicate declaration checks and force
            creation of a new ISCC-ID for the same content (datahash).
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IsccNote'
            examples:
              full_example:
                summary: Complete IsccNote with all optional fields
                value:
                  iscc_code: "ISCC:KACWN77F73NA44D6EUG3S3QNJIL2BPPQFMW6ZX6CZNOKPAK23S2IJ2I"
                  datahash: "1e205ca7815adcb484e9a136c11efe69c1d530176d549b5d18d038eb5280b4b3470c"
                  metahash: "1e202335f74fc18e2f4f99f0ea6291de5803e579a2219e1b4a18004fc9890b94e598"
                  nonce: "000faa3f18c7b9407a48536a9b00c4cb"
                  timestamp: "2025-01-15T12:00:00.000Z"
                  gateway: "https://example.com/iscc_id/{iscc_id}/metadata"
                  units:
                  - "ISCC:AADWN77F73NA44D6X3N4VEUAPOW5HJKGK5JKLNGLNFPOESXWYDVDVUQ"
                  - "ISCC:EADSKDNZNYGUUF5AMFEJLZ5P66CP5YKCOA3X7F36RWE4CIRCBTUWXYY"
                  - "ISCC:GAD334BLFXWN7QWLCSBGJMLRZW73FFNV7ORVUKN23UWPKGQCWTIHQKY"
                  signature:
                    version: "ISCC-SIG v1.0"
                    controller: "did:web:example.com"
                    pubkey: "z6MkmeDbeC5BecFmVnTHA5PWEBaVUrGLdB3weGE2KYnXfHso"
                    proof: "z5j9nrpPw3oYSAN4XbCvk2sUtkwrueTD6V2Y35gS1KFTode2ED2YQWokPmoXw6QBYtYEFxtAQfzBhdNyr8PMwP79G"
              minimal_example:
                summary: Minimal IsccNote with only required fields
                value:
                  iscc_code: "ISCC:KACWN77F73NA44D6EUG3S3QNJIL2BPPQFMW6ZX6CZNOKPAK23S2IJ2I"
                  datahash: "1e205ca7815adcb484e9a136c11efe69c1d530176d549b5d18d038eb5280b4b3470c"
                  nonce: "000faa3f18c7b9407a48536a9b00c4cb"
                  timestamp: "2025-01-15T12:00:00.000Z"
                  signature:
                    version: "ISCC-SIG v1.0"
                    controller: "did:web:example.com"
                    pubkey: "z6MkmeDbeC5BecFmVnTHA5PWEBaVUrGLdB3weGE2KYnXfHso"
                    proof: "znTcLukuu7CL8FpoaSxr6UWQpxCogZUCZ9iqx9dnP3inkzGszbUN79qrxWvpxEHnuNtLQ5Jd1rBukY7g1JSiYHVZ"
      responses:
        '201':
          description: Declaration successful - ISCC-ID created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IsccReceipt'
        '400':
          description: Bad Request - Client error (malformed request, validation errors, etc.). Returns the first error encountered.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized - Invalid signature or authentication. Returns the first error encountered.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Conflict - Duplicate declaration detected. Use X-Force-Declaration header to override.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: Unprocessable Entity - Validation failed. Returns the first validation error encountered.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /declaration/{iscc_id}:
    delete:
      summary: Delete ISCC-ID
      description: |
        Delete a previously timestamped ISCC declaration. The deletion request must be signed
        by the same controller that created the original declaration.

        **Side Effects:**
        - A deletion event is logged in the Event table with a new sequence number
        - The deletion is timestamped with microsecond precision
      operationId: delete_declaration
      parameters:
        - name: iscc_id
          in: path
          required: true
          schema:
            type: string
            pattern: "^ISCC:[A-Z2-7]{16}$"
          description: The ISCC-ID of the declaration to delete
          example: "ISCC:MAACCD3C6YZJ4IQM"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IsccNoteDelete'
            examples:
              delete_example:
                summary: Delete declaration request
                value:
                  iscc_id: "ISCC:MAACCD3C6YZJ4IQM"
                  timestamp: "2025-01-15T12:00:00.000Z"
                  nonce: "000faa3f18c7b9407a48536a9b00c4cb"
                  signature:
                    version: "ISCC-SIG v1.0"
                    controller: "did:web:example.com"
                    pubkey: "z6MkmeDbeC5BecFmVnTHA5PWEBaVUrGLdB3weGE2KYnXfHso"
                    proof: "z5j9nrpPw3oYSAN4XbCvk2sUtkwrueTD6V2Y35gS1KFTode2ED2YQWokPmoXw6QBYtYEFxtAQfzBhdNyr8PMwP79G"
      responses:
        '204':
          description: No Content - Declaration successfully deleted
        '400':
          description: Bad Request - Client error (malformed request, validation errors, etc.)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized - Invalid signature or not authorized to delete this declaration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found - ISCC-ID does not exist or declaration already deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '422':
          description: Unprocessable Entity - Validation failed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    ErrorResponse:
      $ref: './schemas/ErrorResponse.yaml'
    IsccReceipt:
      $ref: './schemas/IsccReceipt.yaml'
    IsccSignature:
      $ref: './schemas/IsccSignature.yaml'
    IsccNote:
      $ref: './schemas/IsccNote.yaml'
    IsccNoteDelete:
      $ref: './schemas/IsccNoteDelete.yaml'
